### PR TITLE
Fixes #45. Switch away from local readonly and use local -r.

### LINKED ISSUE #45: Fix local / readonly usage
The Gruntwork Installer is still using our old, incorrect bash pattern of declaring variables:

```bash
local readonly foo="bar"
```

Combining `local` and `readonly` this way doesn't actually work. We need to change to:

```bash
local -r foo="bar"
```

Or, in the case of arrays:

```bash
local -ar foo=("aaa" "bbb")
```

### PR DESCRIPTION
**Pull request by jeckhart**
I started this in #44 but realized it's probably cleaner to split this out and then rebase #44 on top of it.

### CODE REVIEW

File: gruntwork-install [hunk 1]
```diff
@@ -202,36 +202,36 @@ function get_os_arch_gox_format {
...
 
 function run_module {
-  local readonly module_name="$1"
-  local readonly download_dir="$2"
+  local -r module_name="$1"
+  local -r download_dir="$2"
   shift 2
-  local readonly module_params=($@)
-  local readonly install_script_path="${download_dir}/${module_name}/${MODULE_INSTALL_FILE_NAME}"
+  local -r module_params=($@)
```
Comment (brikis98) [inline gruntwork-install:233]:
```suggestion
  local -ar module_params=($@)
```

File: modules/packer-file-copy/install-scripts/copy-packer-files.sh [hunk 2]
```diff
@@ -24,18 +24,18 @@ set -e
 readonly DEFAULT_PACKER_FILES_PATH="/tmp/packer-files"
 
 function copy_packer_files {
-  local readonly file_upload_paths=("$DEFAULT_PACKER_FILES_PATH")
-  local readonly script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+  local -r file_upload_paths=("$DEFAULT_PACKER_FILES_PATH")
```
Comment (brikis98) [inline modules/packer-file-copy/install-scripts/copy-packer-files.sh:27]:
```suggestion
  local -ar file_upload_paths=("$DEFAULT_PACKER_FILES_PATH")
```

**Comment by brikis98** [comment]
Tests passed! Merging now.
